<a href="https://colab.research.google.com/github/hwahyeon/Study/blob/main/%EB%A8%B8%EC%8B%A0%20%EB%9F%AC%EB%8B%9D%20(codeit)/01_02_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy로 행렬 사용하기

In [1]:
import numpy as np

In [6]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
C = np.random.rand(3, 5)

C

array([[0.18733523, 0.91209589, 0.52110965, 0.40348465, 0.18490569],
       [0.90418337, 0.01176967, 0.60158171, 0.00623564, 0.51669149],
       [0.62568144, 0.69534611, 0.74552765, 0.11026807, 0.93249214]])

In [5]:
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [9]:
# python에서는 0부터 셈

A[0][2]

2

In [10]:
# 행렬 요소별 곱하기 Element-wise Multiplication

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

A*B

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

In [19]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [21]:
# 행렬 합
A + B

array([[ 1.09509223, -0.5972545 ,  2.1381759 ],
       [ 3.55326235,  2.72486219,  2.74439447],
       [ 4.06289985,  1.07253726,  2.89554637]])

In [22]:
# 행렬과 스칼라 곱
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [23]:
# 행렬끼리 곱
np.dot(A, B)
A @ B

array([[-0.33237042, -0.17704217,  1.18487417],
       [ 1.51760109,  2.8030354 ,  3.6944094 ],
       [ 1.05943097,  2.48091872,  3.08819082]])

In [24]:
# 전치 행렬

A_transpose = np.transpose(A)
A_transpose

A_trans = A.T
A_trans

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [25]:
# 단위 행렬
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [27]:
# 역행렬
# pinv는 역행렬이 없으면 최대한 비슷한 효과를 내는 행렬을 반환함.
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [28]:
# 곱해서 단위행렬이 나오면 역행렬이 맞음.
A @ A_inverse

# 0에 가까운 수가 나오는 것은 컴퓨터가 소수0를 다룰 떄 완벽하게 표현하기 어렵기 때문이다.

array([[ 1.00000000e+00,  4.44089210e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])